---
title: "WordPred"
author: "10-2023 by PP"
format: revealjs
editor: visual
---

## Introduction to WordPred bbb

This project is the final part of a 10 course [Data Science track by Johns Hopkins University on Coursera](https://www.coursera.org/specializations/jhu-data-science). Asignment was to clean and analyze a large corpus of unstructured text and build a word prediction model and use it in a web application.

-   Shiny app WordPred is available [here](https://pavel-droid.shinyapps.io/WordPred/).

-   Code used to prepare model, create an app is available [here](https://github.com/Pavel-droid/SwiftKey-Capstone).

## Data preparation

30000 lines from three files with natural language data have been used

Corpus, tokens, n-grams and document feature matrixes have been created

-   tokens have been cleaned - removed numbers, punctuation, urls, symbols, stemmed

Data tables with words of n-grams and n-gram frequencies have been created and saved as rds files

## Model accuracy

When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```
